# -*- coding: utf-8 -*-
"""choice dataset.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rMOjAV6Mtme3MDG2MGIHginKmKujeDg1
"""

from zipfile import ZipFile
import shutil
import random
import os
import argparse
parser = argparse.ArgumentParser(description='Script to generate random samples from a dataset')
parser.add_argument('dataset_id',metavar='dataset_id',type=str,help='1: Cars, 2: dog, 3: sky, 4: cultivated land, 5: cats')
args = parser.parse_args()
ip = args.dataset_id

datasets = ["Cars","dog","sky","cultivated land",'cats']
d = datasets[int(ip)-1]

print(f'Dataset Selected: {d}')

parent_dir = f"./inputs/"
try:
    shutil.rmtree(os.path.join(parent_dir,f"sample_{d}"))
except OSError as e:
    print("Warning: %s - %s." % (e.filename, e.strerror)+"  rmtree not required!")

# if(d=='Cars'):
Dir = f"./DATA repository/{d}/"
S = os.listdir(Dir)
r4=random.sample(range(0,len(S)),5)
S1=[]   
for i in r4:
  S1.append(os.path.join(Dir,S[i]))
path= f"./inputs/sample_{d}/"
# os.mkdir(path)
isExist = os.path.exists(path)
if not isExist:
    os.makedirs(path)
for i in S1:
  shutil.copy('{}'.format(i),path)

